language: go
sudo: false

# Only the last two Go releases are supported by the Go team with security
# updates. Any versions older than that should be considered deprecated.
# Don't bother testing with them. tip builds your code with the latest
# development version of Go. This can warn you that your code will break
# in the next version of Go. Later we declare that test runs
# are allowed to fail on Go tip.
go:
  - 1.9
  - tip 

# Skip the install step. Don't `go get` dependencies. Only build with the
# code in vendor/
# install: true

matrix:
  # It's ok if our code fails on unstable development versions of Go.
  allow_failures:
    - go: tip
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true

# Don't email me the results of the test runs.
notifications:
  email: false

# Anything in before_script that returns a nonzero exit code will
# flunk the build and immediately stop. It's sorta like having
# set -e enabled in bash. 
before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - go get github.com/golang/lint/golint                        # Linter
  - go get honnef.co/go/tools/cmd/megacheck                     # Static analyzer/linter
  - go get github.com/fzipp/gocyclo                             
  - go get golang.org/x/tools/cmd/cover                         # Test coverage
  - go get github.com/mattn/goveralls

# Script always run to completion (set +e). All of these code checks are must haves
# in a modern Go project.
script:
# - test -z $(gofmt -s -l $GO_FILES)         # Fail if a .go file hasn't been formatted with gofmt
  - go test -v -race ./...                   # Run all the tests with the race detector enabled
  - go vet ./...                             # go vet is the official Go static analyzer
# - megacheck ./...                          # "go vet on steroids" + linter
  - gocyclo -over 19 $GO_FILES               # Forbid code with huge functions
  - golint -set_exit_status $(go list ./...) # Another linter
  - $GOPATH/bin/goveralls -service=travis-ci
before_deploy:
- go build ./cmd/fridgems 
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: h9EfMQ0EbEtkDRc47lIp5l7TUUrv+1HCJdEFSWMrUmzTk/Hepg77GSf/aUEss2fA9ieiT9e2erbPJEU49dt0eJxhNycYc7RWS5gxBqDGseTWoIn0oqIhYe3OamA+xd2FgnYJZGbrPFNJcvhKS9ptxdzxhHVnK99GZarcoaOCYLHNtORMs3AlXJww2wa6xR0HeyqIqVbBIQFQuEcnvWJ1O+E1ItW3ZBocERStsL7/79thMq5W9R+UGesvJiQZ8oBPya7Pn5DFFZdW8svwGLKWLHBIPASmrxhrzC+yrmJz4fdmCGf3fU118kKdFAwPAFZlyqe63qvAW26zoK+d2I5PZe3Kg4gLlt7O7idRm09Os/EJcgNI2HKNVqg6xV8HmiPCjUPnaras2pBIJyjm7fHTwiZydLf0GKxoKheUB1KKWu/u5L1Na2CKrT2BlQ2BwAkOBTWqowTqcf3HcvimVkkZ08vbNxVyoq0MAiQdEpPL1YXNFLO4zfgaBQNyGk7pXOn/5KIrBvf20v7WvFDOrF78IDWC5+ic/7mLO82ZyPfh6Ck9vgxzgmSiP37iho+j0oc9Nl6I0YR5OLcSh9B517AwS6pL+psNBRUxIOqME3cofxspHZUDf9+6HnLQ86ElyY2AUxdPcXp0pU6mKhW4LzMXXfTdVR/P+WyKAYlaYQwLtSs=
  on: master
  app: shms-fridgems
  file: fridgems
