language: go
sudo: false
go:
    - tip
matrix:
    fast_finish: true
notifications:
    email: false
before_script:
    - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/megacheck
    - go get github.com/fzipp/gocyclo
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
script:
    - go test -v -race ./...
    - go vet ./...
    - gocyclo -over 19 $GO_FILES
    - golint -set_exit_status $(go list ./...)
    - "$GOPATH/bin/goveralls -service=travis-ci"
