// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	EventStore
	DevMeta
	SetDevInitConfigRequest
	SetDevInitConfigResponse
	SaveDevDataRequest
	SaveDevDataResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// EventStore is for NATS pub/sub
type EventStore struct {
	AggregateId   string `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId" json:"aggregate_id,omitempty"`
	AggregateType string `protobuf:"bytes,2,opt,name=aggregate_type,json=aggregateType" json:"aggregate_type,omitempty"`
	EventId       string `protobuf:"bytes,3,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
	EventType     string `protobuf:"bytes,4,opt,name=event_type,json=eventType" json:"event_type,omitempty"`
	EventData     string `protobuf:"bytes,5,opt,name=event_data,json=eventData" json:"event_data,omitempty"`
}

func (m *EventStore) Reset()                    { *m = EventStore{} }
func (m *EventStore) String() string            { return proto.CompactTextString(m) }
func (*EventStore) ProtoMessage()               {}
func (*EventStore) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EventStore) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

func (m *EventStore) GetAggregateType() string {
	if m != nil {
		return m.AggregateType
	}
	return ""
}

func (m *EventStore) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *EventStore) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *EventStore) GetEventData() string {
	if m != nil {
		return m.EventData
	}
	return ""
}

type DevMeta struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Mac  string `protobuf:"bytes,3,opt,name=mac" json:"mac,omitempty"`
}

func (m *DevMeta) Reset()                    { *m = DevMeta{} }
func (m *DevMeta) String() string            { return proto.CompactTextString(m) }
func (*DevMeta) ProtoMessage()               {}
func (*DevMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DevMeta) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DevMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DevMeta) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type SetDevInitConfigRequest struct {
	Time int64    `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Meta *DevMeta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
}

func (m *SetDevInitConfigRequest) Reset()                    { *m = SetDevInitConfigRequest{} }
func (m *SetDevInitConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*SetDevInitConfigRequest) ProtoMessage()               {}
func (*SetDevInitConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SetDevInitConfigRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *SetDevInitConfigRequest) GetMeta() *DevMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type SetDevInitConfigResponse struct {
	Config []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (m *SetDevInitConfigResponse) Reset()                    { *m = SetDevInitConfigResponse{} }
func (m *SetDevInitConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*SetDevInitConfigResponse) ProtoMessage()               {}
func (*SetDevInitConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SetDevInitConfigResponse) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

type SaveDevDataRequest struct {
	Time int64    `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Meta *DevMeta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	Data []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *SaveDevDataRequest) Reset()                    { *m = SaveDevDataRequest{} }
func (m *SaveDevDataRequest) String() string            { return proto.CompactTextString(m) }
func (*SaveDevDataRequest) ProtoMessage()               {}
func (*SaveDevDataRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SaveDevDataRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *SaveDevDataRequest) GetMeta() *DevMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *SaveDevDataRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SaveDevDataResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *SaveDevDataResponse) Reset()                    { *m = SaveDevDataResponse{} }
func (m *SaveDevDataResponse) String() string            { return proto.CompactTextString(m) }
func (*SaveDevDataResponse) ProtoMessage()               {}
func (*SaveDevDataResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SaveDevDataResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*EventStore)(nil), "api.EventStore")
	proto.RegisterType((*DevMeta)(nil), "api.DevMeta")
	proto.RegisterType((*SetDevInitConfigRequest)(nil), "api.SetDevInitConfigRequest")
	proto.RegisterType((*SetDevInitConfigResponse)(nil), "api.SetDevInitConfigResponse")
	proto.RegisterType((*SaveDevDataRequest)(nil), "api.SaveDevDataRequest")
	proto.RegisterType((*SaveDevDataResponse)(nil), "api.SaveDevDataResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CenterService service

type CenterServiceClient interface {
	SetDevInitConfig(ctx context.Context, in *SetDevInitConfigRequest, opts ...grpc.CallOption) (*SetDevInitConfigResponse, error)
	SaveDevData(ctx context.Context, in *SaveDevDataRequest, opts ...grpc.CallOption) (*SaveDevDataResponse, error)
}

type centerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCenterServiceClient(cc *grpc.ClientConn) CenterServiceClient {
	return &centerServiceClient{cc}
}

func (c *centerServiceClient) SetDevInitConfig(ctx context.Context, in *SetDevInitConfigRequest, opts ...grpc.CallOption) (*SetDevInitConfigResponse, error) {
	out := new(SetDevInitConfigResponse)
	err := grpc.Invoke(ctx, "/api.CenterService/SetDevInitConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centerServiceClient) SaveDevData(ctx context.Context, in *SaveDevDataRequest, opts ...grpc.CallOption) (*SaveDevDataResponse, error) {
	out := new(SaveDevDataResponse)
	err := grpc.Invoke(ctx, "/api.CenterService/SaveDevData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CenterService service

type CenterServiceServer interface {
	SetDevInitConfig(context.Context, *SetDevInitConfigRequest) (*SetDevInitConfigResponse, error)
	SaveDevData(context.Context, *SaveDevDataRequest) (*SaveDevDataResponse, error)
}

func RegisterCenterServiceServer(s *grpc.Server, srv CenterServiceServer) {
	s.RegisterService(&_CenterService_serviceDesc, srv)
}

func _CenterService_SetDevInitConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDevInitConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterServiceServer).SetDevInitConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CenterService/SetDevInitConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterServiceServer).SetDevInitConfig(ctx, req.(*SetDevInitConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CenterService_SaveDevData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDevDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterServiceServer).SaveDevData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CenterService/SaveDevData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterServiceServer).SaveDevData(ctx, req.(*SaveDevDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CenterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.CenterService",
	HandlerType: (*CenterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetDevInitConfig",
			Handler:    _CenterService_SetDevInitConfig_Handler,
		},
		{
			MethodName: "SaveDevData",
			Handler:    _CenterService_SaveDevData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x4d, 0x4f, 0xfa, 0x70,
	0x0c, 0xc7, 0xff, 0xfb, 0x0f, 0x41, 0x0a, 0x18, 0x52, 0x13, 0x99, 0x44, 0x12, 0x5c, 0x62, 0xe2,
	0x45, 0x0e, 0xf8, 0x0e, 0x64, 0x1e, 0x38, 0x18, 0xe3, 0xe6, 0x59, 0x53, 0x59, 0x5d, 0x76, 0xd8,
	0x83, 0x5b, 0x59, 0xc2, 0x1b, 0xf2, 0xea, 0x5b, 0x34, 0xeb, 0xc6, 0x83, 0x12, 0x4e, 0xde, 0xda,
	0x7e, 0xdb, 0x4f, 0xbf, 0xbf, 0xe6, 0x07, 0x6d, 0x4a, 0xc3, 0x49, 0x9a, 0x25, 0x92, 0xa0, 0x49,
	0x69, 0x68, 0x7f, 0x19, 0x00, 0xf7, 0x05, 0xc7, 0xe2, 0x49, 0x92, 0x31, 0x5e, 0x42, 0x97, 0x82,
	0x20, 0xe3, 0x80, 0x84, 0x5f, 0x43, 0xdf, 0x32, 0xc6, 0xc6, 0x75, 0xdb, 0xed, 0x6c, 0x6a, 0x73,
	0x1f, 0xaf, 0xe0, 0x64, 0xdb, 0x22, 0xab, 0x94, 0xad, 0xff, 0xda, 0xd4, 0xdb, 0x54, 0x9f, 0x57,
	0x29, 0xe3, 0x39, 0x1c, 0x73, 0xc9, 0x2d, 0x29, 0xa6, 0x36, 0xb4, 0x34, 0x9f, 0xfb, 0x38, 0x02,
	0xa8, 0x24, 0x9d, 0x6e, 0xa8, 0xd8, 0xd6, 0x8a, 0x4e, 0x6e, 0x64, 0x9f, 0x84, 0xac, 0xa3, 0x1d,
	0xd9, 0x21, 0x21, 0x7b, 0x06, 0x2d, 0x87, 0x8b, 0x07, 0x16, 0x42, 0x84, 0x86, 0x22, 0x2a, 0x97,
	0x1a, 0x97, 0xb5, 0x98, 0xa2, 0xb5, 0x29, 0x8d, 0xb1, 0x0f, 0x66, 0x44, 0x8b, 0xda, 0x46, 0x19,
	0xda, 0x8f, 0x30, 0xf0, 0x58, 0x1c, 0x2e, 0xe6, 0x71, 0x28, 0xb3, 0x24, 0x7e, 0x0f, 0x03, 0x97,
	0x3f, 0x96, 0x9c, 0x8b, 0x42, 0xc3, 0xa8, 0x82, 0x9a, 0xae, 0xc6, 0x38, 0x86, 0x46, 0xc4, 0x42,
	0x0a, 0xed, 0x4c, 0xbb, 0x93, 0xf2, 0x88, 0xb5, 0x09, 0x57, 0x15, 0x7b, 0x0a, 0xd6, 0x3e, 0x30,
	0x4f, 0x93, 0x38, 0x67, 0x3c, 0x83, 0xe6, 0x42, 0x2b, 0xca, 0xec, 0xba, 0x75, 0x66, 0xbf, 0x00,
	0x7a, 0x54, 0xb0, 0xc3, 0x45, 0xf9, 0xb0, 0x3f, 0xed, 0x2f, 0xa7, 0xf4, 0x5c, 0xa6, 0x6e, 0xd0,
	0xd8, 0xbe, 0x81, 0xd3, 0x1f, 0xfc, 0xad, 0x9d, 0x5c, 0x48, 0x96, 0x79, 0x7d, 0xb7, 0x3a, 0x9b,
	0x7e, 0x1a, 0xd0, 0x9b, 0x71, 0x2c, 0x9c, 0x79, 0x9c, 0x15, 0xe1, 0x82, 0xf1, 0x09, 0xfa, 0xbf,
	0x1f, 0x85, 0x17, 0xba, 0xfc, 0xc0, 0xf1, 0x86, 0xa3, 0x03, 0x6a, 0xb5, 0xda, 0xfe, 0x87, 0x77,
	0xd0, 0xd9, 0xf1, 0x84, 0x83, 0xaa, 0x7f, 0xef, 0x0a, 0x43, 0x6b, 0x5f, 0x58, 0x33, 0xde, 0x9a,
	0xfa, 0x7f, 0x6f, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x40, 0xe3, 0xf0, 0x1c, 0xcc, 0x02, 0x00,
	0x00,
}
