// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fridgems.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	fridgems.proto

It has these top-level messages:
	FridgeConfigRequest
	FridgeConfigResponse
	DevMeta
	FridgeData
	FridgeDataRequest
	FridgeDataResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FridgeConfigRequest struct {
	TurnedOn    bool   `protobuf:"varint,1,opt,name=turnedOn" json:"turnedOn,omitempty"`
	CollectFreq int64  `protobuf:"varint,2,opt,name=collectFreq" json:"collectFreq,omitempty"`
	SendFreq    int64  `protobuf:"varint,3,opt,name=sendFreq" json:"sendFreq,omitempty"`
	Mac         string `protobuf:"bytes,4,opt,name=mac" json:"mac,omitempty"`
}

func (m *FridgeConfigRequest) Reset()                    { *m = FridgeConfigRequest{} }
func (m *FridgeConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*FridgeConfigRequest) ProtoMessage()               {}
func (*FridgeConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FridgeConfigRequest) GetTurnedOn() bool {
	if m != nil {
		return m.TurnedOn
	}
	return false
}

func (m *FridgeConfigRequest) GetCollectFreq() int64 {
	if m != nil {
		return m.CollectFreq
	}
	return 0
}

func (m *FridgeConfigRequest) GetSendFreq() int64 {
	if m != nil {
		return m.SendFreq
	}
	return 0
}

func (m *FridgeConfigRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type FridgeConfigResponse struct {
	TurnedOn    bool   `protobuf:"varint,1,opt,name=turnedOn" json:"turnedOn,omitempty"`
	CollectFreq int64  `protobuf:"varint,2,opt,name=collectFreq" json:"collectFreq,omitempty"`
	SendFreq    int64  `protobuf:"varint,3,opt,name=sendFreq" json:"sendFreq,omitempty"`
	Mac         string `protobuf:"bytes,4,opt,name=mac" json:"mac,omitempty"`
}

func (m *FridgeConfigResponse) Reset()                    { *m = FridgeConfigResponse{} }
func (m *FridgeConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*FridgeConfigResponse) ProtoMessage()               {}
func (*FridgeConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FridgeConfigResponse) GetTurnedOn() bool {
	if m != nil {
		return m.TurnedOn
	}
	return false
}

func (m *FridgeConfigResponse) GetCollectFreq() int64 {
	if m != nil {
		return m.CollectFreq
	}
	return 0
}

func (m *FridgeConfigResponse) GetSendFreq() int64 {
	if m != nil {
		return m.SendFreq
	}
	return 0
}

func (m *FridgeConfigResponse) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type DevMeta struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Mac  string `protobuf:"bytes,3,opt,name=mac" json:"mac,omitempty"`
}

func (m *DevMeta) Reset()                    { *m = DevMeta{} }
func (m *DevMeta) String() string            { return proto.CompactTextString(m) }
func (*DevMeta) ProtoMessage()               {}
func (*DevMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DevMeta) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DevMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DevMeta) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type FridgeData struct {
	TempCam1 map[int64]float32 `protobuf:"bytes,1,rep,name=TempCam1" json:"TempCam1,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	TempCam2 map[int64]float32 `protobuf:"bytes,2,rep,name=TempCam2" json:"TempCam2,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
}

func (m *FridgeData) Reset()                    { *m = FridgeData{} }
func (m *FridgeData) String() string            { return proto.CompactTextString(m) }
func (*FridgeData) ProtoMessage()               {}
func (*FridgeData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FridgeData) GetTempCam1() map[int64]float32 {
	if m != nil {
		return m.TempCam1
	}
	return nil
}

func (m *FridgeData) GetTempCam2() map[int64]float32 {
	if m != nil {
		return m.TempCam2
	}
	return nil
}

type FridgeDataRequest struct {
	Action string      `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	Time   int64       `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Meta   *DevMeta    `protobuf:"bytes,3,opt,name=meta" json:"meta,omitempty"`
	Data   *FridgeData `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
}

func (m *FridgeDataRequest) Reset()                    { *m = FridgeDataRequest{} }
func (m *FridgeDataRequest) String() string            { return proto.CompactTextString(m) }
func (*FridgeDataRequest) ProtoMessage()               {}
func (*FridgeDataRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FridgeDataRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *FridgeDataRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *FridgeDataRequest) GetMeta() *DevMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *FridgeDataRequest) GetData() *FridgeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type FridgeDataResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *FridgeDataResponse) Reset()                    { *m = FridgeDataResponse{} }
func (m *FridgeDataResponse) String() string            { return proto.CompactTextString(m) }
func (*FridgeDataResponse) ProtoMessage()               {}
func (*FridgeDataResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FridgeDataResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*FridgeConfigRequest)(nil), "pb.FridgeConfigRequest")
	proto.RegisterType((*FridgeConfigResponse)(nil), "pb.FridgeConfigResponse")
	proto.RegisterType((*DevMeta)(nil), "pb.DevMeta")
	proto.RegisterType((*FridgeData)(nil), "pb.FridgeData")
	proto.RegisterType((*FridgeDataRequest)(nil), "pb.FridgeDataRequest")
	proto.RegisterType((*FridgeDataResponse)(nil), "pb.FridgeDataResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FridgeService service

type FridgeServiceClient interface {
	SetFridgeData(ctx context.Context, in *FridgeDataRequest, opts ...grpc.CallOption) (*FridgeDataResponse, error)
}

type fridgeServiceClient struct {
	cc *grpc.ClientConn
}

func NewFridgeServiceClient(cc *grpc.ClientConn) FridgeServiceClient {
	return &fridgeServiceClient{cc}
}

func (c *fridgeServiceClient) SetFridgeData(ctx context.Context, in *FridgeDataRequest, opts ...grpc.CallOption) (*FridgeDataResponse, error) {
	out := new(FridgeDataResponse)
	err := grpc.Invoke(ctx, "/pb.FridgeService/SetFridgeData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FridgeService service

type FridgeServiceServer interface {
	SetFridgeData(context.Context, *FridgeDataRequest) (*FridgeDataResponse, error)
}

func RegisterFridgeServiceServer(s *grpc.Server, srv FridgeServiceServer) {
	s.RegisterService(&_FridgeService_serviceDesc, srv)
}

func _FridgeService_SetFridgeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FridgeDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FridgeServiceServer).SetFridgeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FridgeService/SetFridgeData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FridgeServiceServer).SetFridgeData(ctx, req.(*FridgeDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FridgeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FridgeService",
	HandlerType: (*FridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetFridgeData",
			Handler:    _FridgeService_SetFridgeData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fridgems.proto",
}

func init() { proto.RegisterFile("fridgems.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0xcf, 0x8b, 0x9b, 0x40,
	0x14, 0xee, 0xa8, 0x4d, 0x93, 0x27, 0x09, 0xed, 0x34, 0x0d, 0x12, 0x0a, 0x15, 0x4f, 0x1e, 0x8a,
	0xd0, 0xe9, 0x25, 0xb4, 0x97, 0x42, 0xd2, 0xdc, 0x4a, 0xe9, 0xa4, 0xff, 0xc0, 0x44, 0x5f, 0x82,
	0x34, 0x8e, 0x46, 0xc7, 0x40, 0x8e, 0x5d, 0xf6, 0xaf, 0xde, 0xd3, 0xe2, 0xa8, 0x89, 0xe6, 0xb0,
	0xb0, 0x97, 0xbd, 0xbd, 0x5f, 0xdf, 0x7b, 0xdf, 0xfb, 0xde, 0x0c, 0x4c, 0x76, 0x79, 0x1c, 0xed,
	0x31, 0x29, 0x82, 0x2c, 0x4f, 0x55, 0x4a, 0x8d, 0x6c, 0xeb, 0xfd, 0x27, 0xf0, 0x7e, 0xad, 0xc3,
	0xcb, 0x54, 0xee, 0xe2, 0x3d, 0xc7, 0x63, 0x89, 0x85, 0xa2, 0x73, 0x18, 0xaa, 0x32, 0x97, 0x18,
	0xfd, 0x96, 0x0e, 0x71, 0x89, 0x3f, 0xe4, 0x17, 0x9f, 0xba, 0x60, 0x87, 0xe9, 0xe1, 0x80, 0xa1,
	0x5a, 0xe7, 0x78, 0x74, 0x0c, 0x97, 0xf8, 0x26, 0xef, 0x86, 0x2a, 0x74, 0x81, 0x32, 0xd2, 0x69,
	0x53, 0xa7, 0x2f, 0x3e, 0x7d, 0x0b, 0x66, 0x22, 0x42, 0xc7, 0x72, 0x89, 0x3f, 0xe2, 0x95, 0xe9,
	0xdd, 0x11, 0x98, 0xf6, 0x39, 0x14, 0x59, 0x2a, 0x0b, 0x7c, 0x51, 0x12, 0x4b, 0x78, 0xb3, 0xc2,
	0xd3, 0x2f, 0x54, 0x82, 0x52, 0xb0, 0xd4, 0x39, 0x43, 0x3d, 0x72, 0xc4, 0xb5, 0x5d, 0xc5, 0xa4,
	0x48, 0x50, 0xcf, 0x19, 0x71, 0x6d, 0xb7, 0x4d, 0xcc, 0x6b, 0x93, 0x07, 0x02, 0x50, 0x6f, 0xb2,
	0x12, 0x4a, 0xd0, 0x05, 0x0c, 0xff, 0x62, 0x92, 0x2d, 0x45, 0xf2, 0xc5, 0x21, 0xae, 0xe9, 0xdb,
	0xec, 0x63, 0x90, 0x6d, 0x83, 0x6b, 0x45, 0xd0, 0xa6, 0x7f, 0x4a, 0x95, 0x9f, 0xf9, 0xa5, 0xba,
	0x83, 0x64, 0x8e, 0xf1, 0x14, 0x92, 0xf5, 0x91, 0x6c, 0xfe, 0x1d, 0xc6, 0xbd, 0xa6, 0x15, 0xcb,
	0x7f, 0x78, 0xd6, 0xcb, 0x98, 0xbc, 0x32, 0xe9, 0x14, 0x5e, 0x9f, 0xc4, 0xa1, 0xac, 0x97, 0x31,
	0x78, 0xed, 0x7c, 0x33, 0x16, 0xa4, 0x03, 0x66, 0xcf, 0x06, 0x7b, 0xf7, 0x04, 0xde, 0x5d, 0x09,
	0xb6, 0x0f, 0x69, 0x06, 0x03, 0x11, 0xaa, 0x38, 0x95, 0x8d, 0x9c, 0x8d, 0xa7, 0x45, 0x8e, 0x1b,
	0x41, 0x4d, 0xae, 0x6d, 0xfa, 0x09, 0xac, 0x04, 0x95, 0xd0, 0x8a, 0xda, 0xcc, 0xae, 0x36, 0x6e,
	0x6e, 0xc2, 0x75, 0x82, 0x7a, 0x60, 0x45, 0x42, 0x09, 0x7d, 0x37, 0x9b, 0x4d, 0xfa, 0x92, 0x70,
	0x9d, 0xf3, 0x3e, 0x03, 0xed, 0xb2, 0x68, 0x9e, 0xd2, 0x0c, 0x06, 0x85, 0x12, 0xaa, 0x2c, 0x5a,
	0x1a, 0xb5, 0xc7, 0xfe, 0xc0, 0xb8, 0xae, 0xde, 0x60, 0x7e, 0x8a, 0x43, 0xa4, 0x3f, 0x60, 0xbc,
	0x41, 0xd5, 0x39, 0xe2, 0x87, 0x9b, 0x29, 0xf5, 0x5e, 0xf3, 0xd9, 0x6d, 0xb8, 0x1e, 0xe4, 0xbd,
	0xda, 0x0e, 0xf4, 0xef, 0xfa, 0xfa, 0x18, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xfc, 0xc1, 0xf2, 0x6f,
	0x03, 0x00, 0x00,
}
